### ISSUE TITLE
Словарь: е/э (фронт, бэк)

### ISSUE THREAD

**Issue by Melodyn** [Hexlet/documentation-style-guide#6]
Предлагаю задокументировать и прорефакторить в проекте разнописание слов фронтэнд и бэкэнд, дабы избежать ситуаций, когда в рамках одного видимого блока текста может оказаться несколько вариантов: бекенд / бекэнд / бэкэнд / бэкенд

Исходя из того, как звучат "энд" и "бэк", особенно в русском, где есть некая деформация, думаю, резонно принять за стандарт написания "э" во всех случаях:
* фронтэнд
* бэкэнд

**Comment by lex111** [comment]
Предлагаю воспользоваться терминологией из словаря "Веб-стандартов":

https://github.com/web-standards-ru/dictionary/blob/master/dictionary.md#front-end
https://github.com/web-standards-ru/dictionary/blob/master/dictionary.md#back-end

**Comment by Melodyn** [comment]
Словарь - дело хорошее, но почему-то без обоснования именно по е/э. Я тут погуглил и многие сайты (а-ля грамотару http://new.gramota.ru/spravka/buro/search-answer?s=энд) всё-таки акцентируются на "э". Есть даже вот такая выкладка касательно наших терминов:
https://gzom.ru/sukha-teoriya/front-end-back-end-kak-po-russki/

Там резюмирование такое:
Фронт-энд и Бэк-энд

**Comment by lex111** [comment]
Ну как же, была дискуссия на эту [тему](https://github.com/web-standards-ru/dictionary/issues/300), мне кажется, аргументы весьма хорошие там приведены.

> Фронт-энд и Бэк-энд

В 2019 ужасно воспринимается как дефис, так и буква "э". Если посмотрите статьи, книги, то увидите что в основном используется "новое" написание этих слов.  Ни к чему использовать устаревшие варианты, эти термины уже прижились в русском языке и поэтому странно как-то писать иначе.

**Comment by Melodyn** [comment]
Как-то странно писать против правил русского языка в угоду новым веяниям, не принятым за аксиому. Это всё равно что разрешить писать "вообщем, смееться, лудше" и т.п. потому что это массово распространено среди молодёжи.

И уж тем более не менее странно опираться на обсуждение каких-то шести чуваков в интернете, как авторитетный источник.

**Comment by lex111** [comment]
> Это всё равно что разрешить писать "вообщем, смееться, лудше" и т.п. потому что это массово распространено среди молодёжи.

Зачем так передергивать, речь ведь про **заимствования**...

> И уж тем более не менее странно опираться на обсуждение каких-то шести чуваков в интернете, как авторитетный источник.

Я написал еще про статьи и книги, где используется написание через "е".  Получается, все [они](https://www.google.com/search?q=%22%D1%84%D1%80%D0%BE%D0%BD%D1%82%D0%B5%D0%BD%D0%B4%22&oq=%22%D1%84%D1%80%D0%BE%D0%BD%D1%82%D0%B5%D0%BD%D0%B4%22&aqs=chrome..69i57j69i60j0j69i60j0j69i60.7809j0j7&sourceid=chrome&ie=UTF-8) "ошибаются"?

**Comment by Melodyn** [comment]
Не, речь не о том, что кто-то ошибается, а о том, откуда берутся эти самые правила заимствования. Дело в том, что техническая литература на русском - это зачастую плохой перевод, а написанная русскими авторами литература также подвержена некой безграмотности, особенно, в заимствованиях. Я бы предпочёл опираться на какие-то лингвистические выкладки, чем на чьё-то авторство, потому что в таком случае мой авторство тоже можно рассматривать как авторитетный источник :)

**Comment by lex111** [comment]
> Не, речь не о том, что кто-то ошибается, а о том, откуда берутся эти самые правила заимствования. 
 
Как таковых правил заимствований ведь не существует? А можете привести переводы книг с плохим переводом, интересно поизучать? Вообще это не в тему, поскольку тут дело не в переводе, у нас обычное заимствование, хотя эти два термина можно перевести. Однако я все равно не понимаю, термины уже прижились в русском, если посмотреть на разные источники, видно как их _обычно_ пишут люди. Тем более есть словарь, хоть вам это не нравится, но все же он авторитетный источник для многих людей, поэтому не вижу смысла что-то менять.

> Я бы предпочёл опираться на какие-то лингвистические выкладки, чем на чьё-то авторство

В данном случае это не имеет значения, т.к. оба варианта допустимы. Мне кажется, тут нужно определиться с тем, как термин используется в рунете, и все указывает на _определенное_ написание, так зачем от него отказываться? Здесь нет конкретно чьего-либо авторства, в том же словаре приняло участие множество людей, и судя по количеству звезд, для многих - он авторитетный источник. Даже если его не брать в расчет, то в даже просто по анализу употребления терминов, можно сделать однозначный вывод, хотя, конечно, можно объяснить это безграмотностью, да.

**Comment by Melodyn** [comment]
Я не против взять указанный вариант, если его поддержут, собственно, Хекслетовчане )
Нужно бы ещё мнений

**Comment by MityaDementiy** [comment]
@Melodyn, @lex111, добрый день! Добавили правила написания некоторых заимствованных слов, в том числе упомянутых в issue. Выбрали консенсусный вариант написания, который в том числе используется в словаре веб-терминов, в редполитике Т — Ж и других авторитетных источниках. Спасибо за ценные мысли.
